### PR TITLE
use env variables instead of using plain passwords

### PR DESCRIPTION
**Pull request by krasi-georgiev**
Signed-off-by: Krasi Georgiev <8903888+krasi-georgiev@users.noreply.github.com>

### CODE REVIEW

**Comment by blocknonip** [comment]
I don't think this is a good idea, as it requires more environment boilerplate for a user to get a working setup. The intent of this repository is to be used as building blocks, not a production deployment.

**Comment by krasi-georgiev** [comment]
That is only a single env variable $JWT_SECRET.
The $POSTGRES_PASSWORD one will be set to a default "postgres" when not set.


Apart from this change I don't see anything else that needs changing to use it production. If that is not the case can you give some more details on what else would be needed to make it production ready?

**Comment by krasi-georgiev** [comment]
the reason for this change is so that I can just copy and paste the compose file and init scripts without going through each line and removing/changing passwords.
This in my opinion is more work than just exporting these env variables with

export .....

**Comment by brocaar** [comment]
Thanks @krasi-georgiev but I agree with @blocknonip. These files are intended to make it really easy (and predictable) for people to get started as one can simply run `docker-compose up` to spin up an environment. The created databases, users and passwords also matches with the `loraserver.toml` and `lora-app-server.toml` file configuration, so the whole setup is self-contained.

For some users using env. variables is not an issue, but for many it is.

**Comment by krasi-georgiev** [comment]
using `$POSTGRES_PASSWORD` doesn't enforce the user to set this variable as it is set to the default of `postgres` when not set.

This change allows me to just copy and past the skeleton without going through each line every time there is an update to see what changes are required to make it production ready.

**Pull request closed without merging**
